import { ThemeProvider } from "@/components/ThemeComponents/ThemeProvider/theme-provider";
import Footer from "@/components/helperComponents/footer/Footer";
import Navbar from "@/components/helperComponents/navbar/Navbar";
import { AuthProvider } from "@/providers/AuthProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
        
        <body className={inter.className}>
          <AuthProvider>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Navbar/>
          <main>{children}</main>
          <Footer/>
          </ThemeProvider>
          </AuthProvider>
        </body>
     
    </html>
  );
}
